/**
 * Created by Administrator on 2017/2/16/016.
 */
var data = {
    "afterA": 2,
    "countPages": 1,
    "counts": 7,
    "curPage": 1,
    "first": true,
    "hasNext": false,
    "hasPre": false,
    "last": true,
    "list": [{
        "author": "崔爱军 王芳 崔曙光",
        "commentcount": 0,
        "creattime": "2016-09-26 17:50:14",
        "creatuser": "yangyue0224",
        "endtime": null,
        "fend": 0,
        "fgroup": " ",
        "ftabs": " ",
        "ftext": "2015年7月31日，国际奥委会主席巴赫宣布北京携手张家口获得2022年冬季奥林匹克运动会的举办权。北京由此成为全球首个既举办过夏季奥运会又即将举办冬季奥运会的城市。<\/p>",
        "ftype": " ",
        "fulltitle": "",
        "fvote": " ",
        "goodcount": 0,
        "hits": 160,
        "hitsurl": 0,
        "id": 3,
        "intro": "",
        "iscommend": 1,
        "isdeleted": 0,
        "isdownload": 1,
        "isgood": 0,
        "islink": 0,
        "isrecommend": 0,
        "istop": 0,
        "keywords": "",
        "lastuptime": {
            "date": 28,
            "day": 1,
            "hours": 0,
            "minutes": 0,
            "month": 10,
            "nanos": 0,
            "seconds": 0,
            "time": 1480262400000,
            "timezoneOffset": -480,
            "year": 116
        },
        "level": 0,
        "nodeid": 3256,
        "nodeidpath": "_764_3251_3256_",
        "normalcount": 0,
        "order": 0,
        "other": " ",
        "passeduser": "yangyue0224",
        "preview": "/webFile//cmsFile/yangyue0224/nodes/node_3256//2016.9/DSC00479.JPG",
        "returnmsg": " ",
        "source": "米东小学",
        "state": 9,
        "subgroup": " ",
        "subtitle": " ",
        "subtype": " ",
        "title": "米东小学扎实开展“网络安全宣传周”活动",
        "url": null,
        "urlsize": 0,
        "urltype": " ",
        "wrongcount": 0
    }, {
        "author": "李伟",
        "commentcount": 0,
        "creattime": "2016-09-12 16:56:30",
        "creatuser": "yangyue0224",
        "endtime": null,
        "fend": 0,
        "fgroup": " ",
        "ftabs": " ",
        "ftext": "北京，简称“京”，中华人民共和国首都、直辖市、国家中心城市、超大城市，全国政治中心、文化中心、国际交往中心、科技创新中心，是中国共产党中央委员会、中华人民共和国中央人民政府和全国人民代表大会的办公所在地，中国中部战区司令部驻地。<\/p>",
        "ftype": " ",
        "fulltitle": "",
        "fvote": " ",
        "goodcount": 0,
        "hits": 65,
        "hitsurl": 0,
        "id": 6,
        "intro": "",
        "iscommend": 1,
        "isdeleted": 0,
        "isdownload": 1,
        "isgood": 0,
        "islink": 0,
        "isrecommend": 0,
        "istop": 0,
        "keywords": "",
        "lastuptime": {
            "date": 28,
            "day": 1,
            "hours": 0,
            "minutes": 0,
            "month": 10,
            "nanos": 0,
            "seconds": 0,
            "time": 1480262400000,
            "timezoneOffset": -480,
            "year": 116
        },
        "level": 0,
        "nodeid": 3256,
        "nodeidpath": "_764_3251_3256_",
        "normalcount": 0,
        "order": 0,
        "other": " ",
        "passeduser": "yangyue0224",
        "preview": "/webFile//cmsFile/yangyue0224/nodes/node_3256//2016.7/60%E4%B8%AD/IMG_20160617_164612.jpg",
        "returnmsg": " ",
        "source": "山西基础教育网特约通讯员",
        "state": 9,
        "subgroup": " ",
        "subtitle": " ",
        "subtype": " ",
        "title": "教师节，锦旗谢师恩",
        "url": null,
        "urlsize": 0,
        "urltype": " ",
        "wrongcount": 0
    }, {
        "author": "孔小亮",
        "commentcount": 0,
        "creattime": "2016-09-12 16:24:29",
        "creatuser": "yangyue0224",
        "endtime": null,
        "fend": 0,
        "fgroup": " ",
        "ftabs": " ",
        "ftext": "1960年1月7日，撤销昌平区，恢复昌平县；撤销顺义区，恢复顺义县；撤销通州区，恢复通县；撤销大兴区，恢复大兴县；撤销周口店区，恢复房山县。至1960年底，北京市下辖东城、西城、宣武、崇文、海淀、朝阳、丰台、门头沟等8区和昌平、延庆、怀柔、密云、顺义、平谷、通县、大兴、房山等9县。<\/p>",
        "ftype": " ",
        "fulltitle": "",
        "fvote": " ",
        "goodcount": 0,
        "hits": 35,
        "hitsurl": 0,
        "id": 9,
        "intro": "",
        "iscommend": 1,
        "isdeleted": 0,
        "isdownload": 1,
        "isgood": 0,
        "islink": 0,
        "isrecommend": 0,
        "istop": 0,
        "keywords": "",
        "lastuptime": {
            "date": 28,
            "day": 1,
            "hours": 0,
            "minutes": 0,
            "month": 10,
            "nanos": 0,
            "seconds": 0,
            "time": 1480262400000,
            "timezoneOffset": -480,
            "year": 116
        },
        "level": 0,
        "nodeid": 3256,
        "nodeidpath": "_764_3251_3256_",
        "normalcount": 0,
        "order": 0,
        "other": " ",
        "passeduser": "yangyue0224",
        "preview": "/webFile//cmsFile/yangyue0224/nodes/node_3256//2016.9/DSC00479.JPG",
        "returnmsg": " ",
        "source": "阳城县寺头乡中心学校",
        "state": 9,
        "subgroup": " ",
        "subtitle": " ",
        "subtype": " ",
        "title": "寺头乡中心学校开展消防安全教育主题班会活动",
        "url": null,
        "urlsize": 0,
        "urltype": " ",
        "wrongcount": 0
    }, {
        "author": "赵阳",
        "commentcount": 0,
        "creattime": "2016-09-12 15:56:00",
        "creatuser": "yangyue0224",
        "endtime": null,
        "fend": 0,
        "fgroup": " ",
        "ftabs": " ",
        "ftext": "1958年3月，河北省通县专区所属通县、顺义、大兴、良乡、房山等5县及通州市划入北京市。其后撤销西单、西四两区，合并设立西城区；撤销东单、东四二区，合并设立东城区；撤销前门区，并入崇文、宣武二区；东郊区改名为朝阳区；撤销石景山区，分别划归丰台区、海淀区和门头沟区；京西矿区改名为门头沟区；撤销通县和通州市，合并设立通州区；撤销良乡、房山二区，合并设立周口店区；撤销大兴县，改为大兴区；撤销南苑区，划归朝阳区、丰台区和大兴区；撤销顺义县，改为顺义区。<\/p>",
        "ftype": " ",
        "fulltitle": "",
        "fvote": " ",
        "goodcount": 0,
        "hits": 6,
        "hitsurl": 0,
        "id": 11,
        "intro": "",
        "iscommend": 1,
        "isdeleted": 0,
        "isdownload": 1,
        "isgood": 0,
        "islink": 0,
        "isrecommend": 0,
        "istop": 0,
        "keywords": "",
        "lastuptime": {
            "date": 28,
            "day": 1,
            "hours": 0,
            "minutes": 0,
            "month": 10,
            "nanos": 0,
            "seconds": 0,
            "time": 1480262400000,
            "timezoneOffset": -480,
            "year": 116
        },
        "level": 0,
        "nodeid": 3256,
        "nodeidpath": "_764_3251_3256_",
        "normalcount": 0,
        "order": 0,
        "other": " ",
        "passeduser": "yangyue0224",
        "preview": "/webFile//cmsFile/yangyue0224/nodes/node_3256//2016.9/IMG_7578.JPG",
        "returnmsg": " ",
        "source": "山西基础教育网特约通讯员",
        "state": 9,
        "subgroup": " ",
        "subtitle": " ",
        "subtype": " ",
        "title": "北大学子回母校",
        "url": null,
        "urlsize": 0,
        "urltype": " ",
        "wrongcount": 0
    }, {
        "author": "冯敏",
        "commentcount": 0,
        "creattime": "2016-07-14 11:55:02",
        "creatuser": "yangyue0224",
        "endtime": null,
        "fend": 0,
        "fgroup": " ",
        "ftabs": " ",
        "ftext": "明朝初年，以应天府（今南京）为京师，大都路于洪武元年（1368年）八月改称为北平府，同年十月应军事需要划归山东行省。洪武九年（1376年），改为北平承宣布政使司驻地。燕王朱棣经靖难之变后夺得皇位后，于永乐元年（1403年）改北平为北京，是为“行在”（天子行銮驻跸的所在，就称“行在”）且常驻于此，如今的北京也从此得名。永乐十九年（1421年）正月，明朝中央政府正式迁都北京，以顺天府北京为京师，应天府则作为留都称南京。明仁宗、英宗的部分时期，北京还曾一度降为行在，京师复为南京应天府。<\/p>",
        "ftype": " ",
        "fulltitle": "",
        "fvote": " ",
        "goodcount": 0,
        "hits": 214,
        "hitsurl": 0,
        "id": 13,
        "intro": "",
        "iscommend": 1,
        "isdeleted": 0,
        "isdownload": 1,
        "isgood": 0,
        "islink": 0,
        "isrecommend": 0,
        "istop": 0,
        "keywords": "",
        "lastuptime": {
            "date": 28,
            "day": 1,
            "hours": 0,
            "minutes": 0,
            "month": 10,
            "nanos": 0,
            "seconds": 0,
            "time": 1480262400000,
            "timezoneOffset": -480,
            "year": 116
        },
        "level": 0,
        "nodeid": 3256,
        "nodeidpath": "_764_3251_3256_",
        "normalcount": 0,
        "order": 0,
        "other": " ",
        "passeduser": "yangyue0224",
        "preview": "/webFile//cmsFile/yangyue0224/nodes/node_3256//2016.9/IMG_7578.JPG",
        "returnmsg": " ",
        "source": "太原60中",
        "state": 9,
        "subgroup": " ",
        "subtitle": " ",
        "subtype": " ",
        "title": "太原60中举办“嘉雅杯中华经典诵读”比赛",
        "url": null,
        "urlsize": 0,
        "urltype": " ",
        "wrongcount": 0
    }, {
        "author": "崔爱军 任国艳 崔曙光",
        "commentcount": 0,
        "creattime": "2016-07-13 11:10:29",
        "creatuser": "",
        "endtime": null,
        "fend": 0,
        "fgroup": " ",
        "ftabs": " ",
        "ftext": "大蒙古国成吉思汗麾下大将木华黎于嘉定八年（1215年）攻下北京，遂设置燕京路大兴府。元世祖至元元年（1264年）改称中都路大兴府。至元九年（1272年），中都大兴府正式改名为大都路（突厥语：Khanbalik，意为“汗城”，音译为汗八里、甘巴力克），也就是元大都。元大都成为全中国的交通中心，北到岭北行省，东到奴儿干都司（治所黑龙江下游），西到西藏地方，南到海南，都在此交流。从这一时期起，北京成为中国的首都。<\/p>",
        "ftype": " ",
        "fulltitle": "",
        "fvote": " ",
        "goodcount": 0,
        "hits": 168,
        "hitsurl": 0,
        "id": 23,
        "intro": "",
        "iscommend": 1,
        "isdeleted": 0,
        "isdownload": 1,
        "isgood": 0,
        "islink": 0,
        "isrecommend": 0,
        "istop": 0,
        "keywords": "",
        "lastuptime": {
            "date": 28,
            "day": 1,
            "hours": 0,
            "minutes": 0,
            "month": 10,
            "nanos": 0,
            "seconds": 0,
            "time": 1480262400000,
            "timezoneOffset": -480,
            "year": 116
        },
        "level": 0,
        "nodeid": 3256,
        "nodeidpath": "_764_3251_3256_",
        "normalcount": 0,
        "order": 0,
        "other": " ",
        "passeduser": "",
        "preview": "/webFile//cmsFile/null/nodes/node_3256//2016.6/IMAG0055.jpg",
        "returnmsg": " ",
        "source": "米东小学",
        "state": 9,
        "subgroup": " ",
        "subtitle": " ",
        "subtype": " ",
        "title": "关爱儿童，携手成长",
        "url": null,
        "urlsize": 0,
        "urltype": " ",
        "wrongcount": 0
    }, {
        "author": "",
        "commentcount": 0,
        "creattime": "2016-07-08 16:14:53",
        "creatuser": "yangyue0224",
        "endtime": null,
        "fend": 0,
        "fgroup": " ",
        "ftabs": " ",
        "ftext": "北京是首批国家历史文化名城和世界上拥有世界文化遗产数最多的城市，三千多年的历史孕育了故宫、天坛、八达岭长城、颐和园等众多名胜古迹。早在七十万年前，北京周口店地区就出现了原始人群部落“北京人”。公元前1045年，北京成为蓟、燕等诸侯国的都城。公元938年以来，北京先后成为辽陪都、金中都、元大都、明清国都。1949年1月1日成为中华人民共和国首都。"
        ,"ftype":" ",
        "fulltitle":"",
        "fvote":" ",
        "goodcount":0,"hits":254,
        "hitsurl":0,
        "id":2,
        "intro":"",
        "iscommend":1,
        "isdeleted":0,
        "isdownload":1,
        "isgood":0,
        "islink":0,
        "isrecommend":0,
        "istop":1,
        "keywords":"",
        "lastuptime":{"date":28,"day":1,"hours":0,"minutes":0,"month":10,"nanos":0,"seconds":0,"time":1480262400000,"timezoneOffset":-480,"year":116},"level":0,"nodeid":3256,"nodeidpath":"_764_3251_3256_","normalcount":0,"order":0,"other":" ","passeduser":"yangyue0224","preview":"/webFile//cmsFile/yangyue0224/nodes/node_3256//2016.7/1.jpg","returnmsg":" ","source":"兴县电教馆","state":9,"subgroup":" ","subtitle":" ","subtype":" ","title":"兴县2016年度理化实验操作及信息技术考试在一二零师学校进行","url":null,"urlsize":0,"urltype":" ","wrongcount":0}],"pageSize":10,"preA":2,"sql":"","url":""}
